name: Run Smoke Tests
on:
  push:
    branches:
      - main
  pull_request:
      branches:
        - main
      types: [ opened, synchronize ]
  workflow_dispatch:

jobs:
  smoke-test-epoch-before-340:
    runs-on: self-hosted
    steps:
      - name: â¬‡ï¸ Checkout repository
        uses: actions/checkout@v3

      - name: ğŸ¦¾ Create .env file
        run: |
          echo "PORT=3000" > .env
          echo "REACT_APP_VERSION=$npm_package_version" >> .env
          echo "REACT_APP_API_URL=${EXPLORER_API_MAINNET_URL}" >> .env
          echo "REACT_APP_MAINNET_APP_URL=${EXPLORER_API_MAINNET_URL}" >> .env
          echo "REACT_APP_NETWORK_NAMES=\"{\"mainnet\":\"Mainnet\",\"preprod\":\"Preprod\"}\"" >> .env

      - name: ğŸ«¡ Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: ğŸ§˜â€â™€ï¸ Download dependencies
        run: npm ci

      - name: Generate test script
        run: |
          cd cypress/smoke
          pip3 install numpy requests
          python CypressDynamicScript.py --epochl=100 --epochs=1 --epoche=340 --blockl=1

      - name: ğŸ³ Run tests
        run: npm test
        env:
          DANGEROUSLY_DISABLE_HOST_CHECK: true

      - name: ğŸ“¹ Archive test videos
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: videos
          path: ./cypress/videos

      - name: ğŸ–¼ï¸ Archive test screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: screenshots
          path: ./cypress/screenshots
    env:
      EXPLORER_API_MAINNET_URL: ${{ secrets.EXPLORER_API_MAINNET_URL }}

  smoke-test-epoch-after-340:
    runs-on: self-hosted
    steps:
      - name: â¬‡ï¸ Checkout repository
        uses: actions/checkout@v3

      - name: ğŸ¦¾ Create .env file
        run: |
          echo "PORT=3000" > .env
          echo "REACT_APP_VERSION=$npm_package_version" >> .env
          echo "REACT_APP_API_URL=${EXPLORER_API_MAINNET_URL}" >> .env
          echo "REACT_APP_MAINNET_APP_URL=${EXPLORER_API_MAINNET_URL}" >> .env
          echo "REACT_APP_NETWORK_NAMES=\"{\"mainnet\":\"Mainnet\",\"preprod\":\"Preprod\"}\"" >> .env


      - name: ğŸ«¡ Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: ğŸ§˜â€â™€ï¸ Download dependencies
        run: npm ci

      - name: Generate test script
        run: |
          cd cypress/smoke
          pip3 install numpy requests
          python CypressDynamicScript.py --epochl=100 --epochs=340 --epoche=424 --blockl=1

      - name: ğŸ³ Run tests
        run: npm test

      - name: ğŸ“¹ Archive test videos
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: videos
          path: ./cypress/videos

      - name: ğŸ–¼ï¸ Archive test screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: screenshots
          path: ./cypress/screenshots
    env:
      EXPLORER_API_MAINNET_URL: ${{ secrets.EXPLORER_API_MAINNET_URL }}

  smoke-test:
    runs-on: self-hosted
    steps:
      - name: â¬‡ï¸ Checkout repository
        uses: actions/checkout@v3

      - name: ğŸ¦¾ Create .env file
        run: |
          echo "PORT=3000" > .env
          echo "REACT_APP_VERSION=$npm_package_version" >> .env
          echo "REACT_APP_API_URL=${EXPLORER_API_MAINNET_URL}" >> .env
          echo "REACT_APP_MAINNET_APP_URL=${EXPLORER_API_MAINNET_URL}" >> .env
          echo "REACT_APP_NETWORK_NAMES=\"{\"mainnet\":\"Mainnet\",\"preprod\":\"Preprod\"}\"" >> .env


      - name: ğŸ«¡ Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: ğŸ§˜â€â™€ï¸ Download dependencies
        run: npm ci

      - name: Generate test script
        run: |
          cd cypress/smoke
          pip3 install numpy requests
          python CypressDynamicScript.py

      - name: ğŸ³ Run tests
        run: npm test

      - name: ğŸ“¹ Archive test videos
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: videos
          path: ./cypress/videos

      - name: ğŸ–¼ï¸ Archive test screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: screenshots
          path: ./cypress/screenshots
    env:
      EXPLORER_API_MAINNET_URL: ${{ secrets.EXPLORER_API_MAINNET_URL }}


