name: Run E2E Tests on Integration Environment
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout repository
        uses: actions/checkout@v3

      - name: ğŸ¦¾ Create .env file
        run: |
          echo "PORT=3000" > .env
          echo "REACT_APP_VERSION=$npm_package_version" >> .env
          echo "REACT_APP_API_URL=${secrets.INT_EXPLORER_API_MAINNET_URL}" >> .env
          echo "REACT_APP_MAINNET_APP_URL=${secrets.INT_EXPLORER_API_MAINNET_URL}" >> .env
          echo 'REACT_APP_NETWORK_NAMES="{"mainnet":"Mainnet","preprod":"Preprod"}"' >> .env
          echo "REACT_APP_MAINNET_API_URL=${secrets.INT_EXPLORER_API_MAINNET_URL}" >> .env
          echo "REACT_APP_AUTH_API_URL=${secrets.INT_EXPLORER_AUTH_API_URL}" >> .env
          echo "REACT_APP_NETWORK=mainnet" >> .env
          echo "REACT_APP_JSD_WIDGET_KEY=${secrets.EXPLORER_JSD_WIDGET_KEY}" >> .env

      - name: ğŸ«¡ Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: ğŸ§˜â€â™€ï¸ Download dependencies
        run: npm ci

      - name: ğŸ³ Run tests
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          wait-on: "http://localhost:3000"
          wait-on-timeout: 360

      - name: ğŸ“¹ Archive test videos
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: videos
          path: ./cypress/videos

      - name: ğŸ–¼ï¸ Archive test screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: screenshots
          path: ./cypress/screenshots
