name: Run Smoke Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  smoke-test:
    runs-on: self-hosted
    steps:
      - name: â¬‡ï¸ Checkout repository
        uses: actions/checkout@v3

      - name: ğŸ¦¾ Create .env file
        run: |
          echo "PORT=3000" > .env
          echo "REACT_APP_VERSION=$npm_package_version" >> .env
          echo "REACT_APP_API_URL=${{ secrets.EXPLORER_API_MAINNET_URL }}" >> .env
          echo "REACT_APP_MAINNET_APP_URL=${{ secrets.EXPLORER_API_MAINNET_URL }}" >> .env
          echo 'REACT_APP_NETWORK_NAMES="{"mainnet":"Mainnet","preprod":"Preprod"}"' >> .env
          echo "REACT_APP_MAINNET_API_URL=${{ secrets.EXPLORER_API_MAINNET_URL }}" >> .env
          echo "REACT_APP_AUTH_API_URL=${{ secrets.EXPLORER_AUTH_API_URL }}" >> .env
          echo "REACT_APP_NETWORK=mainnet" >> .env
          echo "REACT_APP_JSD_WIDGET_KEY=${{ secrets.EXPLORER_JSD_WIDGET_KEY }}" >> .env
          echo "REACT_APP_BOLNISI_NAME_API=${{ secrets.REACT_APP_BOLNISI_NAME_API }}" >> .env

      - name: ğŸ«¡ Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: ğŸ§˜â€â™€ï¸ Download dependencies
        run: npm ci

      - name: Generate test script
        run: |
          cd cypress/smoke
          which pip || ( sudo apt update -qq && sudo apt install -y python3-pip )
          pip3 install numpy requests
          python3 CypressDynamicScript.py

      - name: ğŸ³ Run tests
        run: npm test
        env:
          DANGEROUSLY_DISABLE_HOST_CHECK: true

      - name: ğŸ“¹ Archive test videos
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: videos
          path: ./cypress/videos

      - name: ğŸ–¼ï¸ Archive test screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: screenshots
          path: ./cypress/screenshots
    env:
      EXPLORER_API_MAINNET_URL: ${{ secrets.EXPLORER_API_MAINNET_URL }}
